tasks:
  - before: platformio upgrade

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - eamodio.gitlens
    - Atishay-Jain.All-Autocomplete
    - CoenraadS.bracket-pair-colorizer
    - esbenp.prettier-vscode
    - shardulm94.trailing-spaces
