; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
description = Model Implementation of 'false.alarm'
src_dir = src
lib_dir = lib
build_cache_dir = .cache
build_dir = build
default_envs = esp32idf

[env]
lib_ldf_mode = chain+
lib_compat_mode = strict
monitor_speed = 115200
check_skip_packages = yes

[env:esp32idf]
platform = espressif32
framework = espidf
build_type = debug
build_flags =
	-DSAMPLING_RATE_HZ=250
	-DWINDOW_SIZE=100
	-DHISTORY_SIZE_S=20
	-DFLOSS_LANDMARK_S=10
	-DSENSOR_WIDTH=411
	-DSENSOR_SAMPLES=400
	-DSHORT_FILTER=25
	-DWANDER_FILTER=125
	-Wall -fdiagnostics-color=always
build_src_flags =
	-DMAIN_LOG_LEVEL=ESP_LOG_VERBOSE
	-DFILE_DATA=1
	-DLOG_CPU_LOAD=1
board = esp32dev
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
monitor_filters = time
check_tool =
	cppcheck
	clangtidy
	pvs-studio
check_src_filters =
	lib
	src
check_flags =
	cppcheck: --enable=all --addon=cert.py --inline-suppr --suppress=missingIncludeSystem --platform=arm32-wchar_t2 --language=c++ --std=c++17
	clangtidy: --config-file=.clang-tidy
	pvs-studio: --exclude-path=.pio --analysis-mode=62 --platform=arm --errors-off=V2005,V2575,V2533,V2511,V2563,V2600,V2578,V2506,V3163,V3164,V3551,V3539,V3549,V3554

[env:native]
platform = native
test_framework = unity
lib_compat_mode = off
build_flags = -Wall -fdiagnostics-color=always

[env:esp32_test]
platform = espressif32
framework = espidf
board = sparkfun_esp32_iot_redboard
test_framework = unity
build_type = debug
build_flags =
	-DUSE_SD_CARD=1
	-Wall -fdiagnostics-color=always
build_src_flags = -DMAIN_LOG_LEVEL=ESP_LOG_INFO
monitor_speed = 115200
monitor_filters =
	esp32_exception_decoder
	time
upload_speed = 921600
test_port = COM10
test_speed = 115200
